### ISSUE TITLE
is there something wrong in beam_search.py?

### ISSUE THREAD

**Issue by nlp4whp** [abisee/pointer-generator#151]
Sorry, I got stuck in beam_search.py

in each decode_step, topk_ids.shape is [batch_size, beam_size * 2]
so `new_hyp` count should be batch_size * beam_size * 2, 
and for every batch_size of `new_hyp`, we need keep top_beam_size

BUT, in this part (https://github.com/abisee/pointer-generator/blob/master/beam_search.py#L128-L136),
all the `new_hyp` would be append into `all_hyps`, and sort_hyps() would sort all the `new_hyp`, rather than sort and get each top_beam_size for each batch.

Should we sort each batch of `new_hyp`, like:
```
for batch_hyp in all_hyp:
    sort_hyps(hyps)[: beam_size]
```

Am I wrong in this snippet? Thank you

**Comment by nlp4whp** [comment]
Sorry, my mistake, top_beam_size will be calculated in decode_onestep
Thanks

**Comment by iamxpy** [comment]
@nlp4whp Hello, I am wondering on the same question, why do we have to get 2\*beam_size top tokens in a decode step? why not just keep beam_size top tokens? Though I think it is also ok to keep 2\*beam_size top tokens because we will sort all hypothesis and only keep beam_size of them for the next deocode step, but is it not necessary to do so? For example we can also keep all tokens(vocab_size in total) and their log probs, which give us beam_size\*vocab_size hyps every step, and keep beam_size top hyps after sorting them. Am I missing something? Please correct me if I am wrong, thanks!

**Comment by iamxpy** [comment]
**Update**: I notice that when a hypothesis get a [STOP] token but it is not sufficiently long, it will be discarded. This means if we only keep beam_size top tokens, we will probably get less then beam_size hypothesis, and keep 2\*beam_size top tokens will alleviate this phenomenon to some extend (but it cannot be avoided, say we set `min_dec_steps` to infinity, we can't get any valid hyps). Any other ideas?
