### ISSUE TITLE
Tensorboard vis error: vocab_metadata.tsv is not a file

### ISSUE THREAD

**Issue by hate5six** [abisee/pointer-generator#2]
It looks like I'm able to run training and eval concurrently and I'm seeing a generated vocab_metadata.tsv, but when I go to "Embeddings" in Tensorboard I get: 

> log_root/testrun/train/vocab_metadata.tsv is not a file

which is strange since that file exists. Will the visualization work only when I run decode?

**Comment by abisee** [comment]
Hi hate5six,

For me, the embeddings appear in Tensorboard once you've begun training (no decode job necessary). I've never seen that error before. I tried searching for it and [this](http://www.jianshu.com/p/d5339d04aa17) is the only result I found. It seems to say that the problem may be caused by relative vs. absolute paths for log_root.

**Comment by hate5six** [comment]
Looks like absolute paths solves the problem. Thank you so much! Very excited to experiment with this model as I've been seeing poor performance using vanilla textsum (for the reasons you specify in your paper).
