### ISSUE TITLE
Why not tf.scatter_nd_add but tf.scatter_nd in function _calc_final_dist?

### ISSUE THREAD

**Issue by HsuWanTing** [abisee/pointer-generator#22]
I have some problem in attn_dists_projected part in function _calc_final_dist (model.py line 174).
https://github.com/abisee/pointer-generator/blob/master/model.py#L174

I thought that we should add all attention probabilities to the word entries.
For example, if the ith, jth and kth encoder words are the same word w, then we should add a_i, a_j and a_k to the same entry (the index of w in the vocabulary).
But tf.scatter_nd only update the value not add the value. I think this should use tf.scatter_nd_add. Please correct me if I misunderstanding something. Thanks!

**Comment by abisee** [comment]
Hi @HsuWanTing. 

> For example, if the ith, jth and kth encoder words are the same word w, then we should add a_i, a_j and a_k to the same entry (the index of w in the vocabulary).

Yes, that's the intended behaviour. 

> But tf.scatter_nd only update the value not add the value. I think this should use tf.scatter_nd_add. 

What do you mean by "only update the value not add the value"? I see that the (rather cryptic!) `scatter_nd` [documentation](https://www.tensorflow.org/api_docs/python/tf/scatter_nd) says that `scatter_nd` applies "updates". I'm not sure what exactly is meant by this, but from running a small test, the updates seem to be additive. 

e.g. if you take the example given in the documentation:
```
indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([9, 10, 11, 12])
shape = tf.constant([8])
scatter = tf.scatter_nd(indices, updates, shape)
with tf.Session() as sess:
  print sess.run(scatter)
```
which gives `[0, 11, 0, 10, 9, 0, 0, 12]` as output, and alter it so that

```
indices = tf.constant([[4], [3], [4], [7]])
```
then you get `[ 0  0  0 10 20  0  0 12]` as output, showing that 9+11=20 in the index=4 position.

**Comment by HsuWanTing** [comment]
I see. I confused `scatter_nd` in tensorflow with `scatter_` in pytorch.
In pytorch, the output will be `[0, 0, 0, 10, 11, 0, 0, 12]` in the above example. The index=4 position will first be updated to 9, and then updated to 11, not 20 (9+11). 
Sorry for my mistake. Anyway, thanks for your quick reply!
