### ISSUE TITLE
calculation of p_final(w)

### ISSUE THREAD

**Issue by lipiji** [abisee/pointer-generator#27]
Hi,
 In the paper, p_final(w) = p_g * p_gen(w) + (1 - p_g) * p_copy(w).
And  p_copy(w) is the summation of all the attention weight a_i when w_i = w.
But I did not find the code block to calculate this summation of a_i, could some one indicate it  to me?
Thanks~

**Comment by abisee** [comment]
Hi @lipiji, check out the comment starting on [this line](https://github.com/abisee/pointer-generator/blob/master/model.py#L164). `tf.scatter_nd` on [this line](https://github.com/abisee/pointer-generator/blob/master/model.py#L174) is doing the summation you're talking about.

**Comment by lipiji** [comment]
@abisee   thanks.  The purpose of adding up a_i is to handle the repetitive words appear in the source sentence?
Because I also implemented a pointer mechanism in my project but did not obtain improvements.
What  do you think the keypoints which can let the copynet work?
Thanks.

**Comment by abisee** [comment]
1. The purpose of adding up a_i is so that the probability of copying a word w is proportional to the sum of the attention on word w, in all the places w appears in the source text.
2. The pointer mechanism doesn't have any direct supervision. The network learns end-to-end when to copy and when to generate.

**Comment by lipiji** [comment]
@abisee   I see. Thanks.
