### ISSUE TITLE
It seems that text_format is undefined?

### ISSUE THREAD

**Issue by eduOS** [abisee/pointer-generator#36]
In [this line](https://github.com/abisee/pointer-generator/blob/4954f405fc4faab5003ae384ad181eb883e453ea/batcher.py#L364) it seems that the text_format function is not defined. Could anyone please tell me what it is?

**Comment by abisee** [comment]
Hi @eduOS, thanks for pointing this out. `text_format`refers to a package we were using but then removed. I think it was just printing out the example name when there's an error. We didn't spot the problem because that error never seems to occur. It's now been [removed](https://github.com/abisee/pointer-generator/commit/e9bfc3ce97526ed3264a987c78f19a74e8ffe921).
