### ISSUE TITLE
Clarification on paper and implementation

### ISSUE THREAD

**Issue by hashbangCoder** [abisee/pointer-generator#39]
Hi, 

Thanks for releasing the code!

In computing the *p_gen* in [this line](https://github.com/abisee/pointer-generator/blob/master/attention_decoder.py#L158), your input to the linear projection includes the decoder cell state and decoder prev_output (In eq. 8 of the paper)

Any reason why both the cell state and prev_output are used ? Wouldn't that be redundant since the output subsumes the cell state (via the output gate) ? Have you tried using just the output?

**Comment by abisee** [comment]
Hi @hashbangCoder,

What's `prev_output`? I don't see a variable by that name.

In this line

```
p_gen = linear([context_vector, state.c, state.h, x], 1, True)
```

* `context_vector` is the weighted sum of the encoder hidden states (weighted by attention distribution)
* `state` is the current decoder hidden state, where `state.c` is the LSTM cell and `state.h` is the LSTM hidden state
* `x` is the decoder input, which is the word vector after a linear projection (which happens on this [line](https://github.com/abisee/pointer-generator/blob/master/attention_decoder.py#L142))

I assume you're asking why we're using both the LSTM cell _and_ the LSTM hidden state, instead of just  the LSTM state. The answer is we chose to put both in, in case it was useful for the calculation of `p_gen`. Perhaps, as you say, only the LSTM state is necessary. We haven't tried it but you could easily try it yourself to see what happens.

**Comment by hashbangCoder** [comment]
Yes, that was indeed my query. thanks for the reply!
